### ISSUE TITLE
Adicionar puntos pendientes del workshop - Configurar Zalenium (Opcional)

### ISSUE THREAD

**Issue by germandavid85** [AgileTestingColombia/workshop-protractor#25]
Configurar Zalenium (Opcional)

**Comment by diemol** [comment]
Hola, me encontré este issue de pura casualidad. Si necesitan ayuda para configurar Zalenium me dicen, con mucho gusto les puedo ayudar. Saludos.

**Comment by aperdomob** [comment]
Este issue ya fue resuelto, diemol que pena no había visto tu comentario :-(
