### ISSUE TITLE
Crear una imagen docker para travis

### ISSUE THREAD

**Issue by aperdomob** [AgileTestingColombia/workshop-protractor#78]
https://github.com/andredumas/docker-travis-ci-cli/blob/master/Dockerfile

https://hub.docker.com/_/ruby/

https://github.com/travis-ci/travis.rb#installation

**Comment by Scot3004** [comment]
Por que ruby si travis incluye una imagen para nodejs 8 (lts) y nodejs 7

**Comment by aperdomob** [comment]
Porque es para el travis-cli, el necesita de ruby, en el ultimo link esta la documentación
